 
import type { Metadata } from "next";
import {  Public_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";
const publicSans = Public_Sans({
  variable: "--font-public-sans",
  subsets: ["latin"],
}) 

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${publicSans.variable} min-h-svh flex flex-col  antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
